using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MVC.SourceGen
{
    /// <summary>
    /// 为标记了 [MVC.ObservableProperty] 的字段自动生成带变更通知的属性。
    /// 目标类需为 partial，且继承自 MVC.ObservableModel（提供 protected SetValue）。
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ObservablePropertyGenerator : IIncrementalGenerator
    {
        private const string AttributeFullName = "MVC.ObservablePropertyAttribute";

        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace MVC
{
    /// <summary>标记字段以生成带变更通知的属性。</summary>
    [System.AttributeUsage(System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    internal sealed class ObservablePropertyAttribute : System.Attribute
    {
    }
}
";

        // 目标类未声明 partial 时的诊断
        private static readonly DiagnosticDescriptor NotPartialRule = new DiagnosticDescriptor(
            id: "MVCOBS001",
            title: "包含 [ObservableProperty] 字段的类型必须为 partial",
            messageFormat: "类型 '{0}' 使用了 [ObservableProperty]，但未声明为 partial，无法生成属性",
            category: "MVC.ObservableProperty",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1) 注入 attribute 定义，业务侧无需手写
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("ObservablePropertyAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            // 2) 精准筛选带该 attribute 的字段
            IncrementalValuesProvider<FieldInfo?> fields = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    predicate: static (node, _) => node is VariableDeclaratorSyntax,
                    transform: static (ctx, _) => Transform(ctx));

            // 3) 聚合后按类型生成
            context.RegisterSourceOutput(fields.Collect(), static (spc, all) => Emit(spc, all));
        }

        private static FieldInfo? Transform(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IFieldSymbol field)
            {
                return null;
            }

            INamedTypeSymbol containingType = field.ContainingType;

            // 判断包含类型是否 partial
            bool isPartial = containingType.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(t => t.Modifiers.Any(m => m.ValueText == "partial"));

            string? location = null;
            if (!isPartial)
            {
                var syntaxRef = containingType.DeclaringSyntaxReferences.FirstOrDefault();
                location = syntaxRef?.SyntaxTree.FilePath;
            }

            return new FieldInfo(
                Namespace: containingType.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : containingType.ContainingNamespace.ToDisplayString(),
                TypeName: containingType.Name,
                TypeKeyword: containingType.IsRecord ? "record" : (containingType.IsValueType ? "struct" : "class"),
                FieldName: field.Name,
                FieldType: field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                IsPartial: isPartial);
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<FieldInfo?> items)
        {
            var valid = items.Where(f => f is not null).Select(f => f!).ToList();
            if (valid.Count == 0)
            {
                return;
            }

            foreach (var group in valid.GroupBy(f => (f.Namespace, f.TypeName, f.TypeKeyword)))
            {
                var groupList = group.ToList();

                // 非 partial：报错并跳过该类型
                if (groupList.Any(f => !f.IsPartial))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        NotPartialRule, Location.None, group.Key.TypeName));
                    continue;
                }

                string source = BuildSource(group.Key.Namespace, group.Key.TypeName, group.Key.TypeKeyword, groupList);
                string hintName = (group.Key.Namespace is null ? "" : group.Key.Namespace + ".")
                    + group.Key.TypeName + ".ObservableProperty.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string BuildSource(string? ns, string typeName, string typeKeyword, List<FieldInfo> fields)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");

            bool hasNs = !string.IsNullOrEmpty(ns);
            string indent = hasNs ? "    " : "";
            if (hasNs)
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
            }

            sb.Append(indent).Append("partial ").Append(typeKeyword).Append(' ').Append(typeName).AppendLine();
            sb.Append(indent).AppendLine("{");

            var used = new HashSet<string>();
            foreach (var f in fields)
            {
                string propName = ToPropertyName(f.FieldName, f.FieldName, used);
                used.Add(propName);

                sb.Append(indent).Append("    public ").Append(f.FieldType).Append(' ').Append(propName).AppendLine();
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).Append("        get => ").Append(f.FieldName).AppendLine(";");
                sb.Append(indent).Append("        set => SetValue(ref ").Append(f.FieldName).AppendLine(", value);");
                sb.Append(indent).AppendLine("    }");
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("}");
            if (hasNs)
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }

        /// <summary>
        /// 字段名 -> 属性名：剥离 m_ / _ 前缀并首字母大写。
        /// 若与字段名冲突则追加下划线，保证唯一。
        /// </summary>
        private static string ToPropertyName(string fieldName, string original, HashSet<string> used)
        {
            string name = fieldName;
            if (name.StartsWith("m_") && name.Length > 2)
            {
                name = name.Substring(2);
            }
            name = name.TrimStart('_');
            if (name.Length == 0)
            {
                name = "Value";
            }

            name = char.ToUpperInvariant(name[0]) + name.Substring(1);

            // 避免与字段名完全相同（字段本就大写开头时）或与已生成属性重名
            while (name == original || used.Contains(name))
            {
                name += "_";
            }
            return name;
        }

        private sealed class FieldInfo
        {
            public FieldInfo(string? Namespace, string TypeName, string TypeKeyword, string FieldName, string FieldType, bool IsPartial)
            {
                this.Namespace = Namespace;
                this.TypeName = TypeName;
                this.TypeKeyword = TypeKeyword;
                this.FieldName = FieldName;
                this.FieldType = FieldType;
                this.IsPartial = IsPartial;
            }

            public string? Namespace { get; }
            public string TypeName { get; }
            public string TypeKeyword { get; }
            public string FieldName { get; }
            public string FieldType { get; }
            public bool IsPartial { get; }
        }
    }
}
