/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Config
{
	internal enum CfgKeyType { Int, Str }

	public abstract class CfgContainerBase<T> : ICfgContainer where T : class, ICfg
	{
		private CfgKeyType _keyType;
		private Dictionary<int, T> _intKeyMap;
		private Dictionary<string, T> _strKeyMap;

		protected void InitIntKey(int capacity)
		{
			_keyType = CfgKeyType.Int;
			_intKeyMap = new Dictionary<int, T>(capacity);
		}

		protected void InitStrKey(int capacity)
		{
			_keyType = CfgKeyType.Str;
			_strKeyMap = new Dictionary<string, T>(capacity);
		}

		protected void AddInt(int key, T value) => _intKeyMap.Add(key, value);
		protected void AddStr(string key, T value) => _strKeyMap.Add(key, value);
		protected int GetCount() => _keyType == CfgKeyType.Int ? _intKeyMap.Count : _strKeyMap.Count;

		void IBinarySerialize.Deserialize(BinaryReader reader)
		{
			Deserialize(reader);
		}
		void IBinarySerialize.Serialize(BinaryWriter writer)
		{
			Serialize(writer);
		}
		abstract protected void Deserialize(BinaryReader reader);
		abstract protected void Serialize(BinaryWriter writer);

		public T Find(int id)
		{
			if (_keyType == CfgKeyType.Int)
				return _intKeyMap.TryGetValue(id, out var val) ? val : null;
			return null;
		}

		public T Find(string id)
		{
			if (_keyType == CfgKeyType.Str)
				return _strKeyMap.TryGetValue(id, out var val) ? val : null;
			return null;
		}

		public T Find(Func<T, bool> func) => GetValues().FirstOrDefault(func);

		public T[] FindAll() => GetValues().ToArray();

		public T[] FindAll(Func<T, bool> func) => GetValues().Where(func).ToArray();

		internal IEnumerable<T> GetValues()
		{
			if (_keyType == CfgKeyType.Int) return _intKeyMap.Values;
			return _strKeyMap.Values;
		}

		public int Count => GetCount();
	}
}
