/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class GameCfgData
	{
		private Dictionary<Type, ICfgContainer> _cfgDatas;

		public void Deserialize(BinaryReader reader)
		{
			_cfgDatas = new Dictionary<Type, ICfgContainer>();

			ICfgContainer _LanguageCfgContainer = new LanguageCfgContainer();
			_LanguageCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);

			ICfgContainer _GmCfgContainer = new GmCfgContainer();
			_GmCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(GmCfg), _GmCfgContainer);

			ICfgContainer _ActorCfgContainer = new ActorCfgContainer();
			_ActorCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(ActorCfg), _ActorCfgContainer);

			ICfgContainer _ItemCfgContainer = new ItemCfgContainer();
			_ItemCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);

			ICfgContainer _ColorCfgContainer = new ColorCfgContainer();
			_ColorCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(ColorCfg), _ColorCfgContainer);

			ICfgContainer _LoginCfgContainer = new LoginCfgContainer();
			_LoginCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(LoginCfg), _LoginCfgContainer);

		}

		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in _cfgDatas.Values) item.Serialize(writer);
		}

		public CfgContainerBase<T> GetContainer<T>() where T : class, ICfg
		{
			if (_cfgDatas.TryGetValue(typeof(T), out var container))
				return container as CfgContainerBase<T>;
			return null;
		}
	}
}
