/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * AbilityCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class AbilityCfg : ICfg
	{
		public int Id { get; private set; }
		public int[] Segments { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Segments = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Segments.Length; _i++) Segments[_i] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Segments.Length);
			for (int _i = 0; _i < Segments.Length; _i++) writer.Write(Segments[_i]);
		}
	}

	public partial class AbilityCfgContainer : CfgContainerBase<AbilityCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new AbilityCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
