/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * AbilitySegmentCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class AbilitySegmentCfg : ICfg
	{
		public int Id { get; private set; }
		public int Range { get; private set; }
		public int[] FixedEffects { get; private set; }
		public int[] HitEffects { get; private set; }
		public int[] CasterEffects { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Range = reader.ReadInt32();
			FixedEffects = new int[reader.ReadInt32()];
			for (int _i = 0; _i < FixedEffects.Length; _i++) FixedEffects[_i] = reader.ReadInt32();
			HitEffects = new int[reader.ReadInt32()];
			for (int _i = 0; _i < HitEffects.Length; _i++) HitEffects[_i] = reader.ReadInt32();
			CasterEffects = new int[reader.ReadInt32()];
			for (int _i = 0; _i < CasterEffects.Length; _i++) CasterEffects[_i] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Range);
			writer.Write(FixedEffects.Length);
			for (int _i = 0; _i < FixedEffects.Length; _i++) writer.Write(FixedEffects[_i]);
			writer.Write(HitEffects.Length);
			for (int _i = 0; _i < HitEffects.Length; _i++) writer.Write(HitEffects[_i]);
			writer.Write(CasterEffects.Length);
			for (int _i = 0; _i < CasterEffects.Length; _i++) writer.Write(CasterEffects[_i]);
		}
	}

	public partial class AbilitySegmentCfgContainer : CfgContainerBase<AbilitySegmentCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new AbilitySegmentCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
