/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * AbilitySegmentStrikeCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class AbilitySegmentStrikeCfg : ICfg
	{
		public int Id { get; private set; }
		public int Effect { get; private set; }
		public int Hit { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Effect = reader.ReadInt32();
			Hit = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Effect);
			writer.Write(Hit);
		}
	}

	public partial class AbilitySegmentStrikeCfgContainer : CfgContainerBase<AbilitySegmentStrikeCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new AbilitySegmentStrikeCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
