/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * AbilityStrikeCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class AbilityStrikeCfg : ICfg
	{
		public int Id { get; private set; }
		public int RangeRule { get; private set; }
		public int HitRule { get; private set; }
		public int CriticalRule { get; private set; }
		public int[] Effects { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			RangeRule = reader.ReadInt32();
			HitRule = reader.ReadInt32();
			CriticalRule = reader.ReadInt32();
			Effects = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Effects.Length; _i++) Effects[_i] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(RangeRule);
			writer.Write(HitRule);
			writer.Write(CriticalRule);
			writer.Write(Effects.Length);
			for (int _i = 0; _i < Effects.Length; _i++) writer.Write(Effects[_i]);
		}
	}

	public partial class AbilityStrikeCfgContainer : CfgContainerBase<AbilityStrikeCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new AbilityStrikeCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
