/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ActorCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class ActorCfg : ICfg
	{
		public int Id { get; private set; }
		public string PrefabPath { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			PrefabPath = reader.ReadString();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(PrefabPath);
		}
	}

	public partial class ActorCfgContainer : CfgContainerBase<ActorCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ActorCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
