/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * EffectCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class EffectCfg : ICfg
	{
		public int Id { get; private set; }
		public int FormulaType { get; private set; }
		public int FormulaValue { get; private set; }
		public int DamageType { get; private set; }
		public int BaseValue { get; private set; }
		public int[] Arg1 { get; private set; }
		public int[] Arg2 { get; private set; }
		public int[] Arg3 { get; private set; }
		public int[] Arg4 { get; private set; }
		public int[] Arg5 { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			FormulaType = reader.ReadInt32();
			FormulaValue = reader.ReadInt32();
			DamageType = reader.ReadInt32();
			BaseValue = reader.ReadInt32();
			Arg1 = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Arg1.Length; _i++) Arg1[_i] = reader.ReadInt32();
			Arg2 = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Arg2.Length; _i++) Arg2[_i] = reader.ReadInt32();
			Arg3 = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Arg3.Length; _i++) Arg3[_i] = reader.ReadInt32();
			Arg4 = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Arg4.Length; _i++) Arg4[_i] = reader.ReadInt32();
			Arg5 = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Arg5.Length; _i++) Arg5[_i] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(FormulaType);
			writer.Write(FormulaValue);
			writer.Write(DamageType);
			writer.Write(BaseValue);
			writer.Write(Arg1.Length);
			for (int _i = 0; _i < Arg1.Length; _i++) writer.Write(Arg1[_i]);
			writer.Write(Arg2.Length);
			for (int _i = 0; _i < Arg2.Length; _i++) writer.Write(Arg2[_i]);
			writer.Write(Arg3.Length);
			for (int _i = 0; _i < Arg3.Length; _i++) writer.Write(Arg3[_i]);
			writer.Write(Arg4.Length);
			for (int _i = 0; _i < Arg4.Length; _i++) writer.Write(Arg4[_i]);
			writer.Write(Arg5.Length);
			for (int _i = 0; _i < Arg5.Length; _i++) writer.Write(Arg5[_i]);
		}
	}

	public partial class EffectCfgContainer : CfgContainerBase<EffectCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new EffectCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
