/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ItemCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class ItemCfg : ICfg
	{
		public int Id { get; private set; }
		public int Name { get; private set; }
		public string Icon { get; private set; }
		public int Desc { get; private set; }
		public int Backpack { get; private set; }
		public bool Heap { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadInt32();
			Icon = reader.ReadString();
			Desc = reader.ReadInt32();
			Backpack = reader.ReadInt32();
			Heap = reader.ReadBoolean();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Icon);
			writer.Write(Desc);
			writer.Write(Backpack);
			writer.Write(Heap);
		}
	}

	public partial class ItemCfgContainer : CfgContainerBase<ItemCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ItemCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
