/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * LanguageCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class LanguageCfg : ICfg
	{
		public string Id { get; private set; }
		public string Text { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadString();
			Text = reader.ReadString();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Text);
		}
	}

	public partial class LanguageCfgContainer : CfgContainerBase<LanguageCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitStrKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new LanguageCfg();
				item.Deserialize(reader);
				AddStr(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
