/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * LoginCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class LoginCfg : ICfg
	{
		public int Id { get; private set; }
		public string Name { get; private set; }
		public int Sort { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Sort = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Sort);
		}
	}

	public partial class LoginCfgContainer : CfgContainerBase<LoginCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new LoginCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
