/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * SceneCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class SceneCfg : ICfg
	{
		public int Id { get; private set; }
		public string Path { get; private set; }
		public int LoadMode { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Path = reader.ReadString();
			LoadMode = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Path);
			writer.Write(LoadMode);
		}
	}

	public partial class SceneCfgContainer : CfgContainerBase<SceneCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new SceneCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
