/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * SkillCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	public partial class SkillCfg : ICfg
	{
		public int Id { get; private set; }
		public string Name { get; private set; }
		public string Desc { get; private set; }
		public int TargetRule { get; private set; }
		public int Cost { get; private set; }
		public string View { get; private set; }
		public int AbilityId { get; private set; }
		public int HitMdf { get; private set; }
		public int CriticalMdf { get; private set; }
		public int CriticalDamageMdf { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Desc = reader.ReadString();
			TargetRule = reader.ReadInt32();
			Cost = reader.ReadInt32();
			View = reader.ReadString();
			AbilityId = reader.ReadInt32();
			HitMdf = reader.ReadInt32();
			CriticalMdf = reader.ReadInt32();
			CriticalDamageMdf = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Desc);
			writer.Write(TargetRule);
			writer.Write(Cost);
			writer.Write(View);
			writer.Write(AbilityId);
			writer.Write(HitMdf);
			writer.Write(CriticalMdf);
			writer.Write(CriticalDamageMdf);
		}
	}

	public partial class SkillCfgContainer : CfgContainerBase<SkillCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new SkillCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
