/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
*/
namespace ExecelTool
{
	public interface IBinarySerialize
	{
		void Serialize(BinaryWriter writer);
		void Deserialize(BinaryReader reader);
	}
	public interface ICfg : IBinarySerialize
	{
	}
	public interface ICfgList : IBinarySerialize
	{
	}
}
