/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ItemCfg
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace ExecelTool
{
	[Serializable]
	public partial class ItemCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Name {get; private set;} 
		public string Icon {get; private set;} 
		public string Desc {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Icon = reader.ReadString();
			Desc = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Icon);
			writer.Write(Desc);
		}
	}
	[Serializable]
	public partial class ItemCfgList : ICfgList
	{
		public List<ItemCfg> CfgList {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgList = new List<ItemCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ItemCfg();
				item.Deserialize(reader);
				CfgList.Add(item);
			}
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgList)
			{
				item.Serialize(writer);
			}
		}
	}
}
