/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * LanguageCfg
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace ExecelTool
{
	[Serializable]
	public partial class LanguageCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Text {get; private set;} 
		public int Color {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Text = reader.ReadString();
			Color = reader.ReadInt32();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Text);
			writer.Write(Color);
		}
	}
	[Serializable]
	public partial class LanguageCfgList : ICfgList
	{
		public List<LanguageCfg> CfgList {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgList = new List<LanguageCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new LanguageCfg();
				item.Deserialize(reader);
				CfgList.Add(item);
			}
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgList)
			{
				item.Serialize(writer);
			}
		}
	}
}
