/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * WindowCfg
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace ExecelTool
{
	[Serializable]
	public partial class WindowCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Path {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Path = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Path);
		}
	}
	[Serializable]
	public partial class WindowCfgList : ICfgList
	{
		public List<WindowCfg> CfgList {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgList = new List<WindowCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new WindowCfg();
				item.Deserialize(reader);
				CfgList.Add(item);
			}
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgList)
			{
				item.Serialize(writer);
			}
		}
	}
}
