/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ActorCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public sealed class ActorCfg : ICfg
	{
		public int Id {get; private set;} 
		public string PrefabPath {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			PrefabPath = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(PrefabPath);
		}
	}


	[Serializable]
	internal class ActorCfgContainer : CfgContainerBase<ActorCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, ActorCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ActorCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
