/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ColorCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public sealed class ColorCfg : IConfig_IntKey
	{
		public int Id {get; private set;} 
		public string Color {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Color = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Color);
		}
	}


	[Serializable]
	internal class ColorCfgContainer : CfgContainerBase<ColorCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			IntCfgMap = new Dictionary<int, ColorCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ColorCfg();
				item.Deserialize(reader);
				IntCfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(IntCfgMap.Count);
			foreach (var item in IntCfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
