/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public partial class GameCfgData : IBinarySerialize
	{
		public Dictionary<Type, ICfgContainer> CfgDatas {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			CfgDatas = new Dictionary<Type, ICfgContainer>();
			var _LanguageCfgContainer = new LanguageCfgContainer();
			_LanguageCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);
			var _GmCfgContainer = new GmCfgContainer();
			_GmCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(GmCfg), _GmCfgContainer);
			var _WindowCfgContainer = new WindowCfgContainer();
			_WindowCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(WindowCfg), _WindowCfgContainer);
			var _PanelCfgContainer = new PanelCfgContainer();
			_PanelCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(PanelCfg), _PanelCfgContainer);
			var _ActorCfgContainer = new ActorCfgContainer();
			_ActorCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ActorCfg), _ActorCfgContainer);
			var _RoleCfgContainer = new RoleCfgContainer();
			_RoleCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(RoleCfg), _RoleCfgContainer);
			var _HeroCfgContainer = new HeroCfgContainer();
			_HeroCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(HeroCfg), _HeroCfgContainer);
			var _ItemCfgContainer = new ItemCfgContainer();
			_ItemCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);
			var _ColorCfgContainer = new ColorCfgContainer();
			_ColorCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ColorCfg), _ColorCfgContainer);
			var _OverviewMenuCfgContainer = new OverviewMenuCfgContainer();
			_OverviewMenuCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(OverviewMenuCfg), _OverviewMenuCfgContainer);
			var _MonsterCfgContainer = new MonsterCfgContainer();
			_MonsterCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(MonsterCfg), _MonsterCfgContainer);
			var _BattleRoleActionCfgContainer = new BattleRoleActionCfgContainer();
			_BattleRoleActionCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(BattleRoleActionCfg), _BattleRoleActionCfgContainer);
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgDatas.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
