/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public class GameCfgData : IBinarySerialize
	{
		public Dictionary<Type, ICfgContainer> CfgDatas {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			CfgDatas = new Dictionary<Type, ICfgContainer>();
			var _LanguageCfgContainer = new LanguageCfgContainer();
			_LanguageCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);
			var _GmCfgContainer = new GmCfgContainer();
			_GmCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(GmCfg), _GmCfgContainer);
			var _PanelCfgContainer = new PanelCfgContainer();
			_PanelCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(PanelCfg), _PanelCfgContainer);
			var _ActorCfgContainer = new ActorCfgContainer();
			_ActorCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ActorCfg), _ActorCfgContainer);
			var _ItemCfgContainer = new ItemCfgContainer();
			_ItemCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);
			var _ColorCfgContainer = new ColorCfgContainer();
			_ColorCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ColorCfg), _ColorCfgContainer);
			var _LoginCfgContainer = new LoginCfgContainer();
			_LoginCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(LoginCfg), _LoginCfgContainer);
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgDatas.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
