/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GmCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public partial class GmCfg : ICfg
	{
		public int Id {get; private set;} 
		public int Class {get; private set;} 
		public string Name {get; private set;} 
		public string Cmd {get; private set;} 
		public string Args {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Class = reader.ReadInt32();
			Name = reader.ReadString();
			Cmd = reader.ReadString();
			Args = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Class);
			writer.Write(Name);
			writer.Write(Cmd);
			writer.Write(Args);
		}
	}


	[Serializable]
	public partial class GmCfgContainer : CfgContainerBase<GmCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, GmCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new GmCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
