/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * HeroCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public sealed class HeroCfg : IConfig_IntKey
	{
		public int Id {get; private set;} 
		public string Name {get; private set;} 
		public int ActorId {get; private set;} 
		public string HeadIcon {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			ActorId = reader.ReadInt32();
			HeadIcon = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(ActorId);
			writer.Write(HeadIcon);
		}
	}


	[Serializable]
	internal class HeroCfgContainer : CfgContainerBase<HeroCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			IntCfgMap = new Dictionary<int, HeroCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new HeroCfg();
				item.Deserialize(reader);
				IntCfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(IntCfgMap.Count);
			foreach (var item in IntCfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
