/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * LanguageCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public sealed class LanguageCfg : IConfig_StringKey
	{
		public string Id {get; private set;} 
		public string Text {get; private set;} 
		public int Color {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadString();
			Text = reader.ReadString();
			Color = reader.ReadInt32();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Text);
			writer.Write(Color);
		}
	}


	[Serializable]
	internal class LanguageCfgContainer : CfgContainerBase<LanguageCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			StrCfgMap = new Dictionary<string, LanguageCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new LanguageCfg();
				item.Deserialize(reader);
				StrCfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(StrCfgMap.Count);
			foreach (var item in StrCfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
