/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * NavigationGroupCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public partial class NavigationGroupCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Path {get; private set;} 
		public int GroupType {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Path = reader.ReadString();
			GroupType = reader.ReadInt32();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Path);
			writer.Write(GroupType);
		}
	}


	[Serializable]
	public partial class NavigationGroupCfgContainer : CfgContainerBase<NavigationGroupCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, NavigationGroupCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new NavigationGroupCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
