/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * WindowCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Config
{
	[Serializable]
	public sealed class WindowCfg : IConfig_IntKey
	{
		public int Id {get; private set;} 
		public string Path {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Path = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Path);
		}
	}


	[Serializable]
	internal class WindowCfgContainer : CfgContainerBase<WindowCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			IntCfgMap = new Dictionary<int, WindowCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new WindowCfg();
				item.Deserialize(reader);
				IntCfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(IntCfgMap.Count);
			foreach (var item in IntCfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
