/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace Game.Cfg
{
	[Serializable]
	public partial class GameCfgData : IBinarySerialize
	{
		public Dictionary<Type, ICfgList> CfgDatas {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			CfgDatas = new Dictionary<Type, ICfgList>();
			var _LanguageCfgList = new LanguageCfgList();
			_LanguageCfgList.Deserialize(reader);
			CfgDatas.Add(typeof(LanguageCfg), _LanguageCfgList);
			var _WindowCfgList = new WindowCfgList();
			_WindowCfgList.Deserialize(reader);
			CfgDatas.Add(typeof(WindowCfg), _WindowCfgList);
			var _RoleCfgList = new RoleCfgList();
			_RoleCfgList.Deserialize(reader);
			CfgDatas.Add(typeof(RoleCfg), _RoleCfgList);
			var _ItemCfgList = new ItemCfgList();
			_ItemCfgList.Deserialize(reader);
			CfgDatas.Add(typeof(ItemCfg), _ItemCfgList);
			var _ColorCfgList = new ColorCfgList();
			_ColorCfgList.Deserialize(reader);
			CfgDatas.Add(typeof(ColorCfg), _ColorCfgList);
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgDatas.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
