/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	[Serializable]
	public partial class GameCfgData : IBinarySerialize
	{
		public Dictionary<Type, ICfgContainer> CfgDatas {get; private set;}
		public void Deserialize(BinaryReader reader)
		{
			CfgDatas = new Dictionary<Type, ICfgContainer>();
			var _LanguageCfgContainer = new LanguageCfgContainer();
			_LanguageCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);
			var _WindowCfgContainer = new WindowCfgContainer();
			_WindowCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(WindowCfg), _WindowCfgContainer);
			var _RoleCfgContainer = new RoleCfgContainer();
			_RoleCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(RoleCfg), _RoleCfgContainer);
			var _ItemCfgContainer = new ItemCfgContainer();
			_ItemCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);
			var _ColorCfgContainer = new ColorCfgContainer();
			_ColorCfgContainer.Deserialize(reader);
			CfgDatas.Add(typeof(ColorCfg), _ColorCfgContainer);
		}
		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgDatas.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
