/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ItemCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	[Serializable]
	public partial class ItemCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Name {get; private set;} 
		public string Icon {get; private set;} 
		public string Desc {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Icon = reader.ReadString();
			Desc = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Icon);
			writer.Write(Desc);
		}
	}


	[Serializable]
	public partial class ItemCfgContainer : CfgContainerBase<ItemCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, ItemCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ItemCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
