/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * LanguageCfg
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace Game.Cfg
{
	[Serializable]
	public partial class LanguageCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Text {get; private set;} 
		public int Color {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Text = reader.ReadString();
			Color = reader.ReadInt32();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Text);
			writer.Write(Color);
		}
	}
	[Serializable]
	public partial class LanguageCfgContainer : CfgContainerBase<LanguageCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, LanguageCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new LanguageCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
