/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * MonsterCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	[Serializable]
	public partial class MonsterCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Name {get; private set;} 
		public int Actor {get; private set;} 
		public int RoleType {get; private set;} 
		public string HeadIcon {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Actor = reader.ReadInt32();
			RoleType = reader.ReadInt32();
			HeadIcon = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Actor);
			writer.Write(RoleType);
			writer.Write(HeadIcon);
		}
	}


	[Serializable]
	public partial class MonsterCfgContainer : CfgContainerBase<MonsterCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, MonsterCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new MonsterCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
