/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * OverviewMenuCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	[Serializable]
	public partial class OverviewMenuCfg : ICfg
	{
		public int Id {get; private set;} 
		public int Name {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadInt32();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
		}
	}


	[Serializable]
	public partial class OverviewMenuCfgContainer : CfgContainerBase<OverviewMenuCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgMap = new Dictionary<int, OverviewMenuCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new OverviewMenuCfg();
				item.Deserialize(reader);
				CfgMap.Add(item.Id, item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			writer.Write(CfgMap.Count);
			foreach (var item in CfgMap.Values)
			{
				item.Serialize(writer);
			}
		}
	}
}
