/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * RoleCfg
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace Game.Cfg
{
	[Serializable]
	public partial class RoleCfg : ICfg
	{
		public int Id {get; private set;} 
		public string Name {get; private set;} 
		public string PrefabPath {get; private set;} 
		public int RoleType {get; private set;} 
		public string HeadIcon {get; private set;} 
		public void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			PrefabPath = reader.ReadString();
			RoleType = reader.ReadInt32();
			HeadIcon = reader.ReadString();
		}
		public void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(PrefabPath);
			writer.Write(RoleType);
			writer.Write(HeadIcon);
		}
	}
	[Serializable]
	public partial class RoleCfgList : CfgListBase<RoleCfg>
	{
		public override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			CfgList = new List<RoleCfg>(count);
			for (int i = 0; i < count; i++)
			{
				var item = new RoleCfg();
				item.Deserialize(reader);
				CfgList.Add(item);
			}
		}
		public override void Serialize(BinaryWriter writer)
		{
			foreach (var item in CfgList)
			{
				item.Serialize(writer);
			}
		}
	}
}
